#!/usr/bin/env bash
system_type=$(uname -s)

if [ "$system_type" = "Linux" ]; then
  # install zsh, zplug, neovim
  if ! command -v zsh > /dev/null 2>&1; then
    echo "Installing zsh..."
    sudo apt install zsh
  fi
  if ! command -v lf > /dev/null 2>&1; then
    echo "Installing lf"
    cd /tmp
    wget https://github.com/gokcehan/lf/releases/download/r27/lf-linux-amd64.tar.gz
    tar xvf lf-linux-amd64.tar.gz
    sudo mv lf /usr/local/bin
    cd ~
  fi
  if ! command -v lsd > /dev/null 2>&1; then
    echo "Installing lsd"
    cd /tmp
    wget https://github.com/Peltoche/lsd/releases/download/0.21.0/lsd-musl_0.21.0_amd64.deb
    sudo dpkg -i lsd-musl_0.21.0_amd64.deb
    cd ~
  fi
  cd ~/ohmyzsh/plugins
  git clone https://github.com/zsh-users/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
  echo "All packages are installed."
  cd ~
  sudo chsh -s $(which zsh)
fi
